/**
 * STATIC FRAMES — Project data
 * -----------------------------------------------------------
 * Edit this file to add real work. No other files need to change.
 *
 * Each entry:
 *   id          unique string
 *   category    'narrative' | 'commercial' | 'personal'
 *               (commercial covers both commercial and corporate work — they
 *               share one nav item, "Commercial & Corporate")
 *   featured    true = also shows on the homepage "Selected Work" grid
 *   title       project title
 *   client      client / director / production co.
 *   type        'video'   — local video file, plays muted+looped in the grid
 *               'embed'   — hosted on Vimeo/YouTube, tile links out in a new tab
 *               'image'   — a still poster frame, no motion
 *               'placeholder' — no media yet, shows a styled "media pending" tile
 *   thumb       path to a poster/thumbnail image, e.g. 'Media/narrative/my-thumb.jpg'
 *               (also the grid-tile image for type: 'image')
 *   src         path to a local video file (type: 'video'), e.g. 'Media/narrative/my-clip.mp4'
 *               — or, for type: 'image', an optional larger/different image to show
 *               on the project's own page instead of thumb, e.g. 'Media/narrative/my-full.jpg'
 *   embedUrl    full Vimeo/YouTube URL (type: 'embed')
 *   description shown on the project's own page — the brief, your role, notable
 *               techniques or gear used. Leave blank to show a placeholder line.
 *               \n between lines, \n\n for a new paragraph.
 *               **text** for bold, *text* for italic.
 *
 * Drop local files into the matching folder:
 *   Media/narrative/  Media/commercial/  Media/personal/  Media/stills/
 */

const PROJECTS = [
  { id: 'narrative-01', category: 'narrative', featured: true, title: '2026', client: 'NBUK/ Short Doc', type: 'video', thumb: 'Media/narrative/NBUK_Thumb_01.png', src: 'Media/narrative/NBUK_Finals_2026.mp4', embedUrl: '', description: 'Role: Camera Operator, Editor\n Agency: Static Frames \n Client: NBUK (Nepalese Basketball UK League)\n\n*This is a short montage from the NBUK Finals (Nepalese Basketball UK league), which took place in July 2026.*\n\n We’re currently working on a longer piece to explore in depth the motivation of the organisers and volunteers to learn why they do what they do and how they have made it run every single year since 2022.\n\n *(Currently in post-production)*' },
  { id: 'narrative-02', category: 'narrative', featured: true, title: '2026', client: 'The Crab Cake Kid / Short Film', type: 'image', thumb: 'Media/narrative/The Crab Cake Kid-Movie Poster.jpg', src: 'Media/narrative/The Crab Cake Kid-Movie Poster.jpg', embedUrl: '', description: 'Role: Director of Photography\n\n The Crab Cake Kid is an upcoming short film written by acclaimed British comedian and poet Rob Auton. Produced in partnership with the production company Gormville, the film began shooting in early 2025. \n\n *Currently on a film festival run.* \n\n Crew\nDirector: Kirill Teslia\nProducer: Ross McCall\nDOP: Dinesh Thapa\nCamera Operator: Steve Houson, Courtney Andrews\n1st AC: Ben Gorman\n2nd AC: Dan Eden\nScript Supervisor: Sophie Adams\nLighting Assistant: Aga Nawoj\nSound: Jerry Dewing\nRunners: Edmee Duval-Koenig, Eddie Meakin\nHair-Makeup: Maya Cripps, Anna Scott, Elizabeth Sole, Alice Cox\nMusic: Marc Halls, Deist Oelofse, Peter Wicker\nColourist: Sabab Khan\nEditor: Kirill Teslia\nTrailer edit: Sophie Adams\n\nCrabcake Kid: Rob Auton\nChef: Luke McQueen\nWaiter: Homer Todiwala\nCustomer: Charlotte Brown\nRob’s Dad: Tony Coughlan\nKitchen Hand: Sharon\nKitchen Hand 2: Preston James\nTeacher: Suniya Qureshi\nSupporting Actors: Eddna Goke, Ahmore Psiche, Mishael Holdbrook, Paula Hawkins, Faye Sutcliffe, Sophia Louffok, Mairead Barker, Max Kelly, Simeon Jackman-smith, Maria Anastasiades' },
  { id: 'narrative-03', category: 'narrative', featured: false, title: '2023', client: 'A Day at Frozen with West End Actress Emily Lane/ Disney', type: 'embed', thumb: 'Media/narrative/Emily_01.jpg', src: '', embedUrl: 'https://www.youtube.com/watch?v=lEkygHzOoyE&t=5s', description: 'Role: Camera Operator/ Editor\nAgency: Gormville\nClient: Frozen, Disney on Stage\n\nSingle camera shoot with the Frozen, Disney on Stage team. Coordinated and question asked by Gracie Deal and Olga-Marie Pratt\n\n*Emily Lane, currently playing Anna in London’s production of Disney’s Frozen The Musical, takes us behind the scenes and through her pre-show rituals. Being a leading lady in the West End requires a lot of focus, dedication, and, importantly, a big support team on and off stage.*' },
  { id: 'narrative-04', category: 'narrative', featured: false, title: '2023', client: 'Celebrating Shaun Escoffery and George Asprey’s 15th anniversary in London/ The Lion King', type: 'embed', thumb: 'Media/narrative/TLK_02.jpg', src: '', embedUrl: 'https://www.youtube.com/watch?v=qeHwQyt7Sfc', description: 'Role: Camera Operator\nAgency: Gormville\nClient: The Lion King UK\n\n*In April 2023, Shaun Escoffery (Mufasa) and George Asprey (Scar) celebrate 15 years in THE LION KING in London. They thought they were sitting down to talk about their time in the show. They had no idea they were about to be surprised by members of THE LION KING family past and present…*\n\nCrew\nDirector: Steve Houson Producer: Ross McCall, Mihaela Mars\nDOP: Kirill Teslia\nCamera Operator: Dinesh Thapa, Kirill Teslia, Ben Gorman, Kirill Teslia\nPost production team: Ross McCall, Steve Houson, Ben Gorman' },

  { id: 'commercial-01', category: 'commercial', featured: true, title: '2026', client: 'EPK Trailer/ Mamma Mia! The Party', type: 'embed', thumb: 'Media/commercial/MMTP/MMTP_03.png', src: '', embedUrl: 'https://www.youtube.com/watch?v=7YNVmk1U4aw', description: 'Role: Camera Operator (Gimbal)\nAgency: Gormville Client: Mamma Mia! The Party\n\n*Official EPK trailer for Mamma Mia! The Party in O2, London.*\n\nCamera Operators for EPK 2024, 2025 & 2026:\nDinesh Thapa\nBen Gorman\nSteve Houson\nAga Nawoj\nSophie Adams\nSabab Khan\nKirill Teslia\nSammy Purcell' },
  { id: 'commercial-02', category: 'commercial', featured: false, title: '2025', client: 'Komatsu/ Syncron Unlocked', type: 'embed', thumb: 'Media/commercial/Komatsu/Komatsu_01.png', src: '', embedUrl: 'https://fast.wistia.net/embed/iframe/24cq9tzoo7', heroRatio: '2.388', description: 'Role: Camera Operator, Editor\nAgency: Gormville\nClient: Syncron\n\n*Komatsu Forest partnered with Syncron to unify spare parts planning and pricing across its global aftermarket operation. By integrating inventory and pricing data, the company gained centralized control of stock levels and margins—cutting costs, improving availability, and unlocking new growth opportunities worldwide.*\n\nFull story link: [Click here](https://www.syncron.com/customer-stories/komatsu-forest-harnesses-aftermarket-insight-to-drive-global-growth)\n\nCrew\nDirector, Producer: Steve Houson\nCamera Operator: Dinesh Thapa, Sabab Khan\nEditor: Dinesh Thapa\nVisual Effects: Sophie Adams, Felip Docolomansky' },
  { id: 'commercial-03', category: 'commercial', featured: false, title: '2025', client: 'Elvis Evolution: The Immersive Experience/ Layered Reality UK', type: 'embed', thumb: 'Media/commercial/Elvis/Elvis_02.png', src: '', embedUrl: 'https://www.youtube.com/watch?v=M7bPqwtHRp0', description: 'Role: Camera Operator, Editor\nAgency: Gormville\nClient: Layered Reality UK\n\n*Go behind the scenes of Elvis Evolution and hear from the creative team behind this ground breaking immersive experience, launching in London next year! Discover how they’re bringing the King’s legacy to life with cutting-edge technology, stunning visuals, and unforgettable sound. Get an exclusive look at how this multisensory journey is being crafted to immerse you in Elvis’s iconic moments.*\n\nCrew\nProducer: Amy Farrant\nCamera Operator: Dinesh Thapa, Steve Houson\nEditor: Dinesh Thapa' },
  { id: 'commercial-04', category: 'commercial', featured: true, title: '2025', client: 'Circle Of Life: Gala Performance/ The Lion King Musical', type: 'embed', thumb: 'Media/commercial/Rafiki/Rafiki_02.png', src: '', embedUrl: 'https://www.youtube.com/watch?v=BT2J0CwDrI4', description: 'Role: Camera Operator (Gimbal)\nAgency: Gormville\nClient: The Lion King UK\n\n*Not one, not two... but FIVE Rafiki’s from across the world came together to celebrate the 25th anniversary in London 🙌\nOur gala performance featured a one-of-a-kind “Circle of Life” performance, sung in English, German, French, Spanish and Dutch!*\n\nCrew\nCamera Operators:\nDinesh Thapa\nRoss McCall\nKirill Teslia\nAga Nawoj\nSteve Houson\n\nEditing team\nRoss McCall\nSteve Jump' },
  { id: 'commercial-05', category: 'commercial', featured: false, title: '2022', client: '10 year anniversary - London 2012/ Queen Elizabeth Olympic Park', type: 'embed', thumb: 'Media/commercial/Scarlett/Scarlett_03.png', src: '', embedUrl: 'https://www.youtube.com/watch?v=okJdpvvZe4I', description: 'Role: Camera Operator\nAgency: Gormville\nClient: Drew+Rose, QEOP\n\n*Stories highlighted London’s lasting legacy and celebrated the then, now and next moments. These stories shone a light on the incredibly inspiring people who are keeping the 2012 legacy alive and passing the baton to the next generation.*\n\nCrew\nProducer: Emma Cain\nCamera Operator: Dinesh Thapa, Ross McCall\nEditor: Dinesh Thapa\nVisual Effects: Shanshan Liu' },
  { id: 'commercial-06', category: 'commercial', featured: false, title: '2023', client: 'Anaplan Connect Stockholm/ Anaplan', type: 'embed', thumb: 'Media/commercial/Anaplan/Anaplan_02.png', src: '', embedUrl: 'https://www.youtube.com/watch?v=AiluDSzYs28&list=PLriarEWrPWWc4fkNqWWhVw1O6Vmh1a3cW&index=5', description: 'Role: Camera Operator (Broll), Editor\nAgency: Gormville\nClient: Anaplan\n\n*Anaplan Connect Stockholm. One of many Anaplan Connect that we had the pleasure to film. Others include, Paris, London, Zurich, Brussels, including testimonial videos around the world such as Manila, San Francisco, Milan and more.*' },
  { id: 'commercial-07', category: 'commercial', featured: false, title: '2026', client: 'Reveal Video/ Mamma Mia! The Party', type: 'embed', thumb: 'Media/commercial/Peter/Peter_04.png', src: '', embedUrl: 'https://www.facebook.com/reel/937676318751597?locale=en_GB', description: 'Role: Camera Operator\nAgency: Gormville\nClient: Mamma Mia! The Party\n\n*Reveal video as Peter Andre played the role of Nikos in the immersive dining show Mamma Mia! The Party at the O2 Arena in London. His limited run took place for selected performances from May 14 through July 30, 2026.*\n\nCrew\nDirector: Steve Houson and Stacey Haynes\nCamera Operator: Dinesh Thapa\nGaffer: Kirill Teslia\nEditor: Kirill Teslia' },





  { id: 'personal-01', category: 'personal', featured: true, title: '2026', client: 'Two Lives/ Short Film', type: 'image', thumb: 'Media/personal/Two Lives/Two_Lives_03.png', src: 'Media/personal/Two Lives/Two_Lives_01.png', embedUrl: '', description: 'Role: Writer/ Director & Producer\nProduction: Static Frames\n(Currently in post-production)\n\n*Synopsis: On a cold morning outside an office building, an ex-boxer meets a familiar face during a routine security shift, where a single encounter quietly changes the course of his life.*\n\nCrew\nWriter/ Director: Dinesh Thapa\nDOP: Kirill Teslia\nCamera Operator: Sabab Khan\nSound: Thomas Gee\nSpark: Michalina Barczyk\nProduction Assistant: Freddie Barnden\nEditor: Dinesh Thapa\nKit Provider: Gormville\n\nCast\nJason Davies\nFreddie Farrell\nPhilip Honeywell\nBrian Bususu' },
  { id: 'personal-02', category: 'personal', featured: false, title: '2023', client: 'Jhapat Singh Brunel/ Short Doc', type: 'video', thumb: 'Media/personal/JSB/JSB_01.jpg', src: 'Media/personal/Jhapat Singh Bhujel - Short Trailer_compressed.mp4', embedUrl: '', description: 'Role: Camera Operator/ Producer\nProduction: Static Frames\nTalent: Jhapat Singh Bhujel\n\n*Jhapat Singh Bhujel is a short documentary featuring an inspiring individual who relentlessly pursues his dreams while positively impacting those around him.*\n\nFull video link: [Click here](https://www.youtube.com/watch?v=vG-zEOH86kM&t=211s)\n\nCrew\nCamera Operator: Dinesh Thapa\n2nd Camera Operator (Interview)- Nabin Gurung\nEditor: Dinesh Thapa\nKit Provider: Gormville\nSpecial Thanks: Maidstone Gurkha Boxing Club' },
  { id: 'personal-03', category: 'personal', featured: false, title: '2018', client: 'One man, One Passion, One Vision/ Short Doc', type: 'video', thumb: 'Media/personal/Rupak/Rupak24_01.png', src: 'Media/personal/1min Teaser_1080p_compressed.mp4', embedUrl: '', description: 'Role: Camera Operator, Editor\nProduction: Static Frames\nTalent: Rupak Gurung\n\n*Rupak Gurung, a prominent basketball player for Nepal basketball who now serves in the British Armed Forces, reflects on his playing career, life and his future goals.*\n\nFull video link: [Click here](https://www.youtube.com/watch?v=xl4O2ybiHfk&t=22s)\n\nOfficially selected and screened at Kathmandu International Mountain Film Festival 2018.\n\nCrew\nProducer: Ashok Gurung\nCamera Operator: Dinesh Thapa\nMusic: Sleeping at Last, Chris Zabriskie\nSpecial Thanks: Karan Limbu, Ball Driven League, Collis Green Park, Maidstone Basketball' },
  { id: 'personal-04', category: 'personal', featured: false, title: '2016', client: 'I See Myself As An Artist/ Short Doc', type: 'video', thumb: 'Media/personal/ISMAAA/ISMAAA.jpg', src: 'Media/personal/ISeeMyselfAsAnArtist2.0_compressed.mp4', embedUrl: '', description: 'Role: Director, Editor\nTalent: Bishal Rai\n\nOFFICIAL SELECTION - London Cinematic Film Festival 2017\nOFFICIAL SELECTION - UK Screen One International Film Festival 2017\nOFFICIAL SELECTION - The London Monthly Film Festival 2017\nOFFICIAL SELECTION - Screentest: National Student Film Festival 2017\nOFFICIAL SELECTION - Manchester Lift-Off Film Festival Online 2017\nFeatured on - Real Stories Facebook Channel\n\nCrew\nCamera Operators:\nDinesh Thapa\nIrina Iliesei\nZynab Sadik' },
];

/**
 * STILLS — photography grid (about.html uses headshot separately).
 *   ratio  aspect ratio hint for the masonry placeholder, e.g. '4/5', '3/4', '1/1', '16/9'
 *   image  path to the photo, e.g. 'Media/stills/frame-01.jpg'
 */
const STILLS = [
  { id: 'still-01', title: '', ratio: '2/3', image: 'Media/stills/Self-portrait.jpg' },
  { id: 'still-02', title: '', ratio: '1/1', image: 'Media/stills/Morocco.jpg' },
  { id: 'still-03', title: '', ratio: '1/1', image: 'Media/stills/Marrakesh.jpg' },
  { id: 'still-04', title: '', ratio: '3/2', image: 'Media/stills/Night Beach.jpg' },
  { id: 'still-05', title: '', ratio: '3/2', image: 'Media/stills/Venice Lynd.jpg' },
  { id: 'still-06', title: '', ratio: '3/2', image: 'Media/stills/KTM.jpg' },
  { id: 'still-07', title: '', ratio: '3/2', image: 'Media/stills/Bfest.jpg' },
  { id: 'still-08', title: '', ratio: '3/2', image: 'Media/stills/DLR.jpg' },
  { id: 'still-09', title: '', ratio: '2/3', image: 'Media/stills/Karan Miku.jpg' },
  { id: 'still-10', title: '', ratio: '2/3', image: 'Media/stills/Alcatraz.jpg' },
  { id: 'still-11', title: '', ratio: '3/2', image: 'Media/stills/Mum - Nikon D5200.jpg' },
  { id: 'still-12', title: '', ratio: '3/2', image: 'Media/stills/Venice_2016.jpg' },
];
